parameters:
    env(UPDATE_REPOSITORY): 'fayouz/rocket-console'
    env(ROCKET_MAILER_URL): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Billing/Catalogue.php'
            - '../src/Billing/SubscriptionDraft.php'
            - '../src/Billing/InvalidSubscription.php'

when@test:
    services:
        App\Tests\Support\HttpMock: ~
